### PR TITLE
Fix #85, Change EVS_Register failure from SendEvent to WriteToSysLog

### LINKED ISSUE #85: Sends an event message on failure of registering with EVS
**Checklist (Please check before submitting)**

* [x] I reviewed the [Contributing Guide](https://github.com/nasa/DS/blob/main/CONTRIBUTING.md).
* [x] I performed a cursory search to see if the bug report is relevant, not redundant, nor in conflict with other tickets.

**Describe the bug**
`CFE_EVS_SendEvent` is used when `CFE_EVS_Register` fails.  Should use `CFE_ES_WriteToSysLog` for a better chance of actually recording the error.

**Expected behavior**
Use a mechanism for reporting errors that's more likely to succeed in case of an EVS registration failure.

**Code snips**
https://github.com/nasa/DS/blob/04c01548a8eaaf5a1b4abb2b7d7548140e0cd6c0/fsw/src/ds_app.c#L197-L206

**System observed on:**
N/A

**Additional context**
Recommend checking the rest of the apps and marking as bug.

**Reporter Info**
Jacob Hageman - NASA/GSFC

### PR DESCRIPTION
**Pull request by thnkslprpt**
**Checklist**
* [x] I reviewed the [Contributing Guide](https://github.com/nasa/osal/blob/main/CONTRIBUTING.md).
* [x] I signed and emailed the appropriate [Contributor License Agreement](https://github.com/nasa/cFS/blob/main/CONTRIBUTING.md#contributor-license-agreement-cla) to GSFC-SoftwareRelease@mail.nasa.gov and copied cfs-program@lists.nasa.gov.

**Describe the contribution**
Fixes #85
`CFE_EVS_SendEvent` replaced by `CFE_ES_WriteToSysLog` on failure of `CFE_EVS_Register`.

**Testing performed**
GitHub CI actions (incl. Build + Run, Unit Tests etc.) all passing successfully.
Coverage maintained at 100%:
```
  lines......: 100.0% (1311 of 1311 lines)
  functions..: 100.0% (66 of 66 functions)
  branches...: 100.0% (485 of 485 branches)
```

**Expected behavior changes**
Failure can be successfully recorded somewhere even without the EVS now.

**Contributor Info**
Avi Weiss @thnkslprpt

### CODE REVIEW

**Review by skliper — COMMENTED** [review]
Can't send enough props, really appreciate this fix (and checking the other apps)!  I've shifted to project work vs core so much less spare time to work core issues.  Hopefully get back to contributing once I catch up though!

File: unit-test/ds_app_tests.c [hunk 1]
```diff
@@ -179,11 +184,12 @@ void DS_AppInitialize_Test_EVSRegisterError(void)
...
-     * are modified by subfunctions, which we're not testing here */
-    UtAssert_STUB_COUNT(CFE_EVS_SendEvent, 1);
-    UtAssert_INT32_EQ(context_CFE_EVS_SendEvent[0].EventID, DS_INIT_ERR_EID);
-    UtAssert_INT32_EQ(context_CFE_EVS_SendEvent[0].EventType, CFE_EVS_EventType_ERROR);
+    call_count_CFE_EVS_SendEvent = UT_GetStubCount(UT_KEY(CFE_EVS_SendEvent));
+    UtAssert_True(call_count_CFE_EVS_SendEvent == 0, "CFE_EVS_SendEvent was called %u time(s), expected 0",
+                  call_count_CFE_EVS_SendEvent);
+
+    strCmpResult = strncmp(ExpectedSysLogString, context_CFE_ES_WriteToSysLog.Spec, CFE_MISSION_EVS_MAX_MESSAGE_LENGTH);
+    UtAssert_True(strCmpResult == 0, "Sys Log string matched expected result, '%s'", context_CFE_ES_WriteToSysLog.Spec);
```
Comment (skliper) [inline unit-test/ds_app_tests.c:192]: TBH I'd be fine w/ just checkint UtAssert_STUB_COUNT(CFE_ES_WriteToSysLog, 1), no need to confirm 0 events sent.

**Comment by thnkslprpt** [comment]
> Can't send enough props, really appreciate this fix (and checking the other apps)! I've shifted to project work vs core so much less spare time to work core issues. Hopefully get back to contributing once I catch up though!

No worries at all Jake. My pleasure.

File: unit-test/ds_app_tests.c (hunk 1 above)
Comment (thnkslprpt) [reply unit-test/ds_app_tests.c]: Updated.

File: unit-test/ds_app_tests.c [hunk 2]
```diff
@@ -179,11 +184,11 @@ void DS_AppInitialize_Test_EVSRegisterError(void)
     UtAssert_BOOL_FALSE(OS_ObjectIdDefined(DS_AppData.FileStatus[DS_DEST_FILE_CNT / 2].FileHandle));
     UtAssert_BOOL_FALSE(OS_ObjectIdDefined(DS_AppData.FileStatus[DS_DEST_FILE_CNT - 1].FileHandle));
 
-    /* Note: not verifying that rest of DS_AppData is set to 0, because some elements of DS_AppData
-     * are modified by subfunctions, which we're not testing here */
-    UtAssert_STUB_COUNT(CFE_EVS_SendEvent, 1);
-    UtAssert_INT32_EQ(context_CFE_EVS_SendEvent[0].EventID, DS_INIT_ERR_EID);
-    UtAssert_INT32_EQ(context_CFE_EVS_SendEvent[0].EventType, CFE_EVS_EventType_ERROR);
+    call_count_CFE_EVS_SendEvent = UT_GetStubCount(UT_KEY(CFE_EVS_SendEvent));
```
Comment (jphickey) [inline unit-test/ds_app_tests.c:187]: No need to get the stub count of CFE_EVS_SendEvent here that I can see.  Can this be taken out?

File: unit-test/ds_app_tests.c [hunk 3]
```diff
@@ -179,11 +184,11 @@ void DS_AppInitialize_Test_EVSRegisterError(void)
...
+    UtAssert_STUB_COUNT(CFE_ES_WriteToSysLog, 1);
+
+    strCmpResult = strncmp(ExpectedSysLogString, context_CFE_ES_WriteToSysLog.Spec, CFE_MISSION_EVS_MAX_MESSAGE_LENGTH);
+    UtAssert_True(strCmpResult == 0, "Sys Log string matched expected result, '%s'", context_CFE_ES_WriteToSysLog.Spec);
```
Comment (jphickey) [inline unit-test/ds_app_tests.c:191]: I'd also recommend removing the format string text.  We've been removing these rather than updating them.  It does not really add value to the test case.

**Review by jphickey — CHANGES_REQUESTED** [review]
Requested some simplification here.

File: unit-test/ds_app_tests.c (hunk 3 above)
Comment (thnkslprpt) [reply unit-test/ds_app_tests.c]: Cool no worries - If I understood you correctly - I've just left the STUB_COUNT check.

File: unit-test/ds_app_tests.c (hunk 2 above)
Comment (thnkslprpt) [reply unit-test/ds_app_tests.c]: Thanks @jphickey. It must have been left over from a different idea I had for this test case.
Removed now.

**Review by jphickey — CHANGES_REQUESTED** [review]
Just need to check/confirm if that variable needs to be added at all, I think it does not.

File: unit-test/ds_app_tests.c [hunk 4]
```diff
@@ -166,6 +166,10 @@ void DS_AppInitialize_Test_Nominal(void)
 
 void DS_AppInitialize_Test_EVSRegisterError(void)
 {
+    char ExpectedSysLogString[CFE_MISSION_EVS_MAX_MESSAGE_LENGTH];
+    snprintf(ExpectedSysLogString, CFE_MISSION_EVS_MAX_MESSAGE_LENGTH,
+             "DS App: Error registering for Event Services, RC = 0x%%08X\n");
+
```
[the remark this answers is not in the document]
Comment (thnkslprpt) [reply unit-test/ds_app_tests.c]: You're correct - no longer needed since the `UtAssert_True(strCmpResult...` was removed.
Have removed the variable now.

**Review by jphickey — APPROVED** [review]
