### PR TITLE
Fix #60, Apply consistent Event ID names to common events

### LINKED ISSUE #60: Inconsistent Event ID naming
**Checklist**
* [x] I reviewed the [Contributing Guide](https://github.com/nasa/cFS/blob/main/CONTRIBUTING.md).
* [x] I performed a cursory search to see if the bug report is relevant, not redundant, nor in conflict with other tickets.

**Describe the bug**
Copy of https://github.com/nasa/cFE/issues/2175
After finding that there were 9 different Event IDs to indicate the same thing (Invalid Message ID) in https://github.com/nasa/CF/issues/262, I scrubbed the other common commands (e.g. Task Initialisation [INIT], NOOP, Reset Counters etc.) and found the same issue there - almost every component/app had their own variation of the Event ID name for the exact same event.

**Expected behavior**
Apply consistent Event ID names to the events which are common to all/most components and apps.

**Code snips**
Invalid Message ID:
`CFE_EVS_ERR_MSGID_EID`
`CFE_SB_BAD_MSGID_EID`
`CFE_TIME_ID_ERR_EID`
`CS_MID_ERR_EID`
`TO_LAB_MSGID_ERR_EID`
`SAMPLE_APP_INVALID_MSGID_ERR_EID`
`BP_INVALID_MID_ERR_EID`
`SCH_MD_ERR_EID`
`CI_LAB_COMMAND_ERR_EID`

Initialization:
`CFE_TIME_INIT_EID`
`CFE_TBL_INIT_INF_EID`
`CFE_EVS_STARTUP_EID`
`CF_EID_INF_INIT`
`BP_INIT_APP_INFO_EID`
`SCH_INITSTATS_INF_EID`
`CI_LAB_STARTUP_INF_EID`

NOOP:
`CFE_TIME_NOOP_EID`
`CFE_TBL_NOOP_INF_EID`
`CFE_SB_CMD0_RCVD_EID`
`CF_EID_INF_CMD_NOOP`
`FM_NOOP_CMD_EID`
`CI_LAB_COMMANDNOP_INF_EID`

Reset Counters:
`CFE_TIME_RESET_EID`
`CFE_TBL_RESET_INF_EID`
`CFE_EVS_RSTCNT_EID`
`CFE_SB_CMD1_RCVD_EID`
`CF_EID_INF_CMD_RESET`
`SC_RESET_DEB_EID`
`HS_RESET_DBG_EID`
`FM_RESET_CMD_EID`
`HK_RESET_CNTRS_CMD_EID`
`MD_RESET_CNTRS_DBG_EID`
`CI_LAB_COMMANDRST_INF_EID`

etc.

**Reporter Info**
Avi Weiss @thnkslprpt

### PR DESCRIPTION
**Pull request by thnkslprpt**
**Checklist**
* [x] I reviewed the [Contributing Guide](https://github.com/nasa/osal/blob/main/CONTRIBUTING.md).
* [x] I signed and emailed the appropriate [Contributor License Agreement](https://github.com/nasa/cFS/blob/main/CONTRIBUTING.md#contributor-license-agreement-cla) to GSFC-SoftwareRelease@mail.nasa.gov and copied cfs-program@lists.nasa.gov.

**Describe the contribution**
- Fixes #60
  - Consistent event IDs have been applied to the inconsistent cases to align them with a common Event ID naming convention.

**Testing performed**
Only GitHub CI actions.

**Expected behavior changes**
No impact on code behavior (no logic changes).
Consistent Event ID names for the events which are common to all/most cFS components and apps will improve consistency and ease make code review/debugging easier.

**Contributor Info**
Avi Weiss @thnkslprpt

### CODE REVIEW

File: fsw/src/ds_events.h [hunk 1]
```diff
@@ -292,7 +292,7 @@
  *  counters command.  The command is used primarily to clear counters
  *  that have already been examined.
  */
-#define DS_RESET_CMD_EID 33
+#define DS_RESET_INF_EID 33
```
Comment (chillfig) [inline fsw/src/ds_events.h:295]: Line 287 may need a change from `Type: DEBUG` to `Type: INFORMATION`

File: fsw/src/ds_msgdefs.h [hunk 2]
```diff
@@ -70,7 +70,7 @@
  *  \par Command Verification
  *       Evidence of success may be found in the following telemetry:
  *       - #DS_HkPacket_t.CmdAcceptedCounter will reset to zero
- *       - The #DS_RESET_CMD_EID debug event message will be sent
+ *       - The #DS_RESET_INF_EID debug event message will be sent
```
Comment (chillfig) [inline fsw/src/ds_msgdefs.h:73]:
```suggestion
 *       - The #DS_RESET_INF_EID informational event message will be sent
```

**Review by chillfig — CHANGES_REQUESTED** [review]
May need some comment updates about `DS_RESET_INF_EID` and its type now being INFORMATION instead of previously DEBUG.

File: fsw/src/ds_msgdefs.h (hunk 2 above)
Comment (thnkslprpt) [reply fsw/src/ds_msgdefs.h]: Thanks Justin. I've added the updated comments in now.

**Review by chillfig — APPROVED** [review]
Approved. 

The Build and Run workflow in DS is breaking, but due to a null argument in `CFE_EVS_SendEvent()` in /fsw/src/ds_file.c (https://github.com/nasa/DS/actions/runs/3366470370/jobs/5582995262). This pull request only updates Event ID names and does not seem to influence this error/null argument. @dzbaker what do you think?

This workflow also breaks for DS #51 which doesn't directly change /fsw/src/ds_file.c

**Comment by thnkslprpt** [comment]
> Approved.
> 
> The Build and Run workflow in DS is breaking, but due to a null argument in `CFE_EVS_SendEvent()` in /fsw/src/ds_file.c (https://github.com/nasa/DS/actions/runs/3366470370/jobs/5582995262). This pull request only updates Event ID names and does not seem to influence this error/null argument. @dzbaker what do you think?
> 
> This workflow also breaks for DS #51 which doesn't directly change /fsw/src/ds_file.c

Yeah this seems like a separate issue that is only now being triggered in the warnings.
A simple fix might be something like:
image

I can open an issue and submit that change if you think it's suitable.

**Comment by dzbaker** [comment]
> > Approved.
> > The Build and Run workflow in DS is breaking, but due to a null argument in `CFE_EVS_SendEvent()` in /fsw/src/ds_file.c (https://github.com/nasa/DS/actions/runs/3366470370/jobs/5582995262). This pull request only updates Event ID names and does not seem to influence this error/null argument. @dzbaker what do you think?
> > This workflow also breaks for DS #51 which doesn't directly change /fsw/src/ds_file.c
> 
> Yeah this seems like a separate issue that is only now being triggered in the warnings. A simple fix might be something like: image This change results in build + run passing again without any issues. Could also have 'UNKNOWN' or just an empty string in place of 'NULL'. I can open an issue and submit that change if you think it's suitable.

Yes @thnkslprpt, that would be great if you could submit that fix and issue. I'll merge it in with the CCB:FastTrack label so we can try this one again.

**Comment by thnkslprpt** [comment]
> Yes @thnkslprpt, that would be great if you could submit that fix and issue. I'll merge it in with the CCB:FastTrack label so we can try this one again.

No worries mate.
https://github.com/nasa/DS/pull/64

**Comment by dzbaker** [comment]
> > Yes @thnkslprpt, that would be great if you could submit that fix and issue. I'll merge it in with the CCB:FastTrack label so we can try this one again.
> 
> No worries mate. #64

Thanks! Can you rebase this (and #62/#59) with main now that the fix has been merged?

**Comment by chillfig** [comment]
CCB:2023.03.09: Putting on hold until naming conventions for event, etc are merged.

**Comment by dzbaker** [comment]
Hey @thnkslprpt, would you be able to resolve the conflicts? Thanks!

**Review by dzbaker — APPROVED** [review]
